### ISSUE TITLE
There were not enough free threads in the ThreadPool to complete the operation

### ISSUE THREAD

**Issue by ildrada** [Microsoft/Partner-Center-Explorer#12]
Hello,

I am working on a script using the partnercenter powershell module and i am facing a weird behaviour.
I opened a ticket on Microsoft support and they redirect me since all issues related to this module must addressed in this github.

My issue is :
- when i am using the "Get-PartnerCustomerAgreement" call, it is working fine

Howerver, since i have 5000 customer to check, i made a loop and after 40 to 1000 calls, i receive the following error.
![image](https://user-images.githubusercontent.com/59011493/71071297-a0767300-217c-11ea-947e-1503dd1fccc0.png)

Translation in english would be : There were not enough free threads in the ThreadPool to complete the operation

It is working fine on sandbox with the 300 customer we have.

Can you help me solving it ?

Regards,

Arnaud

**Comment by jegraves** [comment]
Issue not related to this project. Suggest posting here: https://github.com/microsoft/Partner-Center-PowerShell/issues
