### ISSUE TITLE
How could get pricing for license-based services using API (REST or Managed) of Microsoft Store Partner Center

### ISSUE THREAD

**Issue by abdellahgrib** [Microsoft/Partner-Center-Explorer#2]
The API of Microsoft Store Partner Center using RateCards returns usage-based services (Azure Services) and can't get license-based services pricing ? I could download the Excel file but my question is , is there any way to get pricing for license-based services using API (REST or Managed) of Microsoft Store Partner Center ?

When getting offers using the API, some information are missing like : ERP Price, List Price, Valid-To Date, Valid-From Date ?

Thanking you

**Comment by ghost** [comment]
@abdelgrib currently there is not a way to obtain pricing for license based services programmatically. This is a request that the product team has received numerous times. I will be sure to pass your request for this year along to them as well. Please let me know if you have any other concerns or questions.

**Comment by davidzerep** [comment]
Two years later, any update on this issue?

**Comment by MaxHogervorst** [comment]
@isaiahwilliams any comments?
